version: '3'
services:
  web:
    build: .
    ports:
      - "5173:5173"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  api:
    build: ../../Node.js/API-Tesis
    ports:
      - "3000:3000"
    volumes:
      - ../../Node.js/API-Tesis:/usr/src/app
      - /usr/src/app/node_modules
